[tool.poetry]
name = "repl_python3_beta_snake"
version = "0.1.0"
description = ""
authors = ["JonZavialov <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
pynput = "^1.7.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
